### ISSUE TITLE
Site is broken!

### ISSUE THREAD

**Issue by rik** [AdrianGaudebert/arewereorganizedyet.com#15]
No update in January, I think this website is not webscale. Or cache invalidation is too difficult to manage properly.

Maybe @etiennesegonzac can shed some light?

**Comment by etiennesegonzac** [comment]
_/me goes to the server room..._

http://img.ifcdn.com/images/5a820ddc5d6ee03234f8e449cd8f617a64a167eac557972e32353d8f1cea0b2c_1.webm

**Comment by adngdb** [comment]
@rik you jealous that there was no entry for your departure maybe? ;-)

**Comment by adngdb** [comment]
https://github.com/adngdb/arewereorganizedyet.com/commit/f9e66a90e0b9ee14aaf0ff0b34138197d1343809
