### ISSUE TITLE
Enable HTTPS?

### ISSUE THREAD

**Issue by annevk** [AdrianGaudebert/arewereorganizedyet.com#52]
It's time.

**Comment by saschanaz** [comment]
Seems this is fixed.

**Comment by annevk** [comment]
It could still redirect and have HSTS, but I guess this is good enough for now. 😊

**Comment by fmarier** [comment]
> I guess this is good enough for now.

But we may as well have it in HTTPS Everywhere :smiley: https://github.com/EFForg/https-everywhere/issues/19903

**Comment by adngdb** [comment]
I have enabled the "enforce HTTPS" option, the site should now automatically be served over HTTPS.

**Comment by pipboy96** [comment]
@adngdb Please also enable [HSTS preloading](https://hstspreload.org/).

**Comment by adngdb** [comment]
@pipboy96 that [does not seem to be supported](https://github.com/isaacs/github/issues/1249) by github pages.
